title: "Research Log"
description: "Diffusion, MultiModal, Foundation Model and Trustworthy AI"
url: "https://leesanghu.github.io"
baseurl: ""
markdown: kramdown
permalink: /paper/:title/
future: true
exclude: [README.md]

